server.port=8081

spring.application.name=ourspring

# Custom variable
creator.name=Deepu
creator.company=Love

# Actuator
management.endpoints.web.exposure.include=health,info,mappings
management.endpoints.web.exposure.exclude=beans
management.info.env.enabled=true

# User access
spring.security.user.name=scott
spring.security.user.password=tiger

# Lazy
spring.main.lazy-initialization=true

# SQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/personal_db
spring.datasource.username=task_man
spring.datasource.password=Magan123

# Adding some information
info.application.creator.name=Deepaks dude
info.application.creator.work=Learning Everything Work

# Log level security mapping
logging.level.org.springframework=error

# Only show ERROR logs for Hibernate
logging.level.org.hibernate=ERROR

# Suppress SQL logs
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF