server.port=8081

spring.application.name=ourspring

# Custom variable
creator.name=Deepu
creator.company=Love

# Actuator
management.endpoints.web.exposure.include=health,info,mappings
management.endpoints.web.exposure.exclude=beans
management.info.env.enabled=true

# User access
spring.security.user.name=scott
spring.security.user.password=tiger

# Lazy
spring.main.lazy-initialization=true

# Adding some information
info.application.creator.name=Deepaks dude
info.application.creator.work=Learning Everything Work

# Log level security mapping
logging.level.org.springframework=debug