server.port=8081

spring.application.name=ourspring

# Custom variable
creator.name=Deepu
creator.company=Love

# Actuator
management.endpoints.web.exposure.include=health,info,beans,mappings
management.info.env.enabled=true

# Adding some information
info.application.creator.name=Deepaks dude
info.application.creator.work=Learning Everything Work